### CREAR USUARIO
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "Carlos Alcaraz",
  "email": "carlos@example.com",
  "birthdate": "1992-06-01"
}


### MOSTRAR USUARIOS
GET http://localhost:3000/users
Content-Type: application/json


### DEPOSITAR
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "userId": 1,
  "type": "DEPOSIT",
  "amount": 3500
}


### RETIRAR
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "userId": 1,
  "type": "WITHDRAW",
  "amount": 500
}

### CREAR STOCK 1
POST http://localhost:3000/stock
Content-Type: application/json

{
  "ticker": "AAPL",
  "name": "Apple"
}

### CREAR STOCK 2
POST http://localhost:3000/stock
Content-Type: application/json

{
  "ticker": "TSLA",
  "name": "Tesla"
}

### CREAR PORTAFOLIO
POST http://localhost:3000/portfolio
Content-Type: application/json

{
  "userId": 1,
  "name": "Acciones regalonas"
}

### COMPRAR
POST http://localhost:3000/order
Content-Type: application/json

{
  "portfolioId": 1,
  "stockId": 1,
  "type": "BUY",
  "amount": 1000
}

### VENDER
POST http://localhost:3000/order
Content-Type: application/json

{
  "portfolioId": 1,
  "stockId": 1,
  "type": "SELL",
  "amount": 400
}

### EDITAR USUARIO
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "fullName": "Carlitos Alcaraz"
}

### EDITAR PORTAFOLIO
PATCH http://localhost:3000/portfolio/1
Content-Type: application/json

{
  "name": "Portafolio regalon"
}

### RESUMEN PORTAFOLIO
GET http://localhost:3000/portfolio/1/summary
Content-Type: application/json

### ULTIMAS ORDENES DE USUARIO
GET http://localhost:3000/order/1/orders?limit=5
Content-Type: application/json