
# CREAR USUARIO
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "Carlos Alcaraz",
  "email": "carlos@example.com",
  "birthdate": "1992-06-01"
}


# MOSTRAR USUARIOS
GET http://localhost:3000/users
Content-Type: application/json


# DEPOSITAR
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "userId": 1,
  "type": "DEPOSIT",
  "amount": 3500
}


# RETIRAR
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "userId": 1,
  "type": "WITHDRAW",
  "amount": 50
}

# CREAR PORTAFOLIO
POST http://localhost:3000/portfolio
Content-Type: application/json

{
  "userId": 1,
  "name": "Nuevo portfolio 2"
}


# COMPRAR
POST http://localhost:3000/order
Content-Type: application/json

{
  "portfolioId": 6,
  "stockId": 1,
  "type": "BUY",
  "amount": 50
}

# VENDER
POST http://localhost:3000/order
Content-Type: application/json

{
  "portfolioId": 6,
  "stockId": 1,
  "type": "SELL",
  "amount": 50
}

# CREAR STOCK
POST http://localhost:3000/stock
Content-Type: application/json

{
  "ticker": "AAPL",
  "name": "Apple"
}

# EDITAR USUARIO
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "fullName": "Carlitos Alcaraz"
}

# EDITAR PORTAFOLIO
PATCH http://localhost:3000/portfolio/5
Content-Type: application/json

{
  "name": "Portafolio moderado"
}

# RESUMEN PORTAFOLIO
GET http://localhost:3000/portfolio/5/summary
Content-Type: application/json

# ULTIMAS ORDENES
GET http://localhost:3000/order/1/orders?limit=5
Content-Type: application/json